### ISSUE TITLE
this.el vs $this.el

### ISSUE THREAD

**Issue by git-e-up** [git-e-up/RESTaurant#3]
Please see the PartyView.js file. Within the printReceipt function, on the 2nd line, I noticed you must not have the $ sign for receipt printing to function properly. In other words, it must be "this.el", not "this.$el".

**Comment by git-e-up** [comment]
I do notice I titled this issue incorrectly. It should read:
"this.el vs this.$el"
The issue, however, remains a mystery to me.

**Comment by amadden80** [comment]
I believe I see the issue.
It is the way you obtain the html later on.
Here are the two options I see as possible:

``` js
var divToPrint = this.el; 
divToPrint.innerHTML;

var divToPrint = this.$el; 
divToPrint.html();
```

This is to say that this won't work:

``` js
var divToPrint = this.$el; 
divToPrint.innerHTML;
```

Note:

``` js
this.$el  // jquery version of the node
this.el   // plain js version of the node
```

_Please close issue when resolved_

**Comment by git-e-up** [comment]
Interesting... is it because you have to use jquery consistently throughout
the function? I didn't realize "this.el" would be picked up by vanilla
javascript.

**Comment by amadden80** [comment]
Just edited my above response..  See the change I made?

**Comment by git-e-up** [comment]
Ah, I do now. Cool. Thanks!
